version: '3'
services:
  app:
    container_name: covid-safe-buildings-backend
    build:
      context: .
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs/
      - ./database.db:/app/database.db
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "5000:80"
    depends_on:
      - app
